export const URL_1_0_17_START_ACTIVITY = "https://i.postimg.cc/44LFFDtZ/image.png"
export const URL_1_0_17_ACTIVITY_1 = "https://i.postimg.cc/QCy497sV/1.png"
export const URL_1_0_17_ACTIVITY_2 = "https://i.postimg.cc/8c5XzH2q/2.png"
export const URL_1_0_17_ACTIVITY_3 = "https://i.postimg.cc/50pkJGRB/3.png"
export const URL_1_0_17_SETTINGS = "https://i.postimg.cc/NMQPWYpG/image.png"
export const URL_1_0_17_PROFILE = "https://i.postimg.cc/8CR0Ksdn/image.png"
export const URL_1_0_17_ACTIVITY_LIST = "https://i.postimg.cc/VNQhWXtC/image.png"

export const URL_1_2_9_STATISTICS = "https://i.postimg.cc/rwtb4fDT/image.png"
export const URL_1_2_9_MONTH_STATISTICS = "https://i.postimg.cc/Fs681MsG/image.png"
export const URL_1_2_9_MONTH_STATISTICS_FILTER = "https://i.postimg.cc/KvjCGGFR/image.png"
export const URL_1_2_9_EXPORT = "https://i.postimg.cc/jqZGYWpp/image.png"

export const URL_1_4_2_ABOUT = "https://i.postimg.cc/8PqhN7N9/about.png"
export const URL_1_4_2_ACTIVITING = "https://i.postimg.cc/c15xbjS4/activiting.png"
export const URL_1_4_2_ACTIVITING_BEFORE = "https://i.postimg.cc/vH1WJrF5/activiting-before.png"
export const URL_1_4_2_ACTIVITING_PREPARE = "https://i.postimg.cc/NGC6CNVg/activiting-prepare.png" // remove?
export const URL_1_4_2_ACTIVITY_CARD = "https://i.postimg.cc/J0FjynJy/activity-card.png"
export const URL_1_4_2_ACTIVITY_GRAPHIC = "https://i.postimg.cc/XN2VzyrC/activity-graphic.png"
export const URL_1_4_2_ACTIVITY_LIST = "https://i.postimg.cc/pTqfHkLJ/activity-list.png"
export const URL_1_4_2_ACTIVITY_TABLE = "https://i.postimg.cc/9MWdKsCf/activity-table.png"
export const URL_1_4_2_ACTIVITY_TYPES = "https://i.postimg.cc/bvfHHs5k/activity-types.png"
export const URL_1_4_2_ADD_ACTIVITY = "https://i.postimg.cc/kgbvbxT7/add-activity.png"
export const URL_1_4_2_EDIT_ACTIVITY_DIALOG =
  "https://i.postimg.cc/m2qSkdNd/edit-activity-dialog.png"
export const URL_1_4_2_EDIT_ROUTE = "https://i.postimg.cc/Bv55hJWy/edit-route.png"
export const URL_1_4_2_EXPORT = "https://i.postimg.cc/SNjry082/export.png"
export const URL_1_4_2_IMPORT = "https://i.postimg.cc/44WPk4KR/import.png"
export const URL_1_4_2_PROFILE = "https://i.postimg.cc/G2rKrHJd/profile.png"
export const URL_1_4_2_SETTINGS = "https://i.postimg.cc/13HpJvMp/settings.png"
export const URL_1_4_2_START = "https://i.postimg.cc/sxgJQqNL/start.png"
export const URL_1_4_2_STATISTICS = "https://i.postimg.cc/25nGP4W0/statistics.png"
export const URL_1_4_2_MONTH_STATISTICS = "https://i.postimg.cc/prcJDkNL/month-statistics.png"
export const URL_1_4_2_STATISTICS_SHORT = "https://i.postimg.cc/fRmnKWZm/statistics-short.png"
export const URL_1_4_2_RESTORE = "https://i.postimg.cc/TY43pWG6/restore-start.png"
