server {
    charset utf-8;
    client_max_body_size 2M;

    server_name train.slaffpro.ru;
    root        /home/train-website/www/public;
    index       index.html;

    access_log  off;
    error_log   /var/log/nginx/train-website_error.log;

    gzip_static on;

    error_page 404 /page-not-found.html;
    error_page 500 /internal-server-error.html;
    proxy_intercept_errors on;

    if ($bad_user_agent) {
        return 444;
    }

    # avoid processing of calls to non-existing static files
    location ~ \.(png|jpg|gif|swf|ico|pdf|zip|rar)$ {
        try_files $uri =404;
        access_log off;
    }
    location ~ \.(js|css)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/index.html $uri.html =404;
    }
    location = /page-not-found {
        return 404;
    }
    location = /internal-server-error {
        return 500;
    }
    location = /page-not-found.html {
        internal;
    }
    location = /internal-server-error.html {
        internal;
    }

    location ~* /\. {
        deny all;
    }

    # + https settings managed by Certbot
}
